### ISSUE TITLE
VS Compatibility

### ISSUE THREAD

**Issue by DesrosiersC** [mlorbetske/VSAssemblyLoadDebugger#1]
Hi,
It is not clear what versions of VS are supported.
The page on the marketplace says VS 2017 but the installer seems to be looking for VS 2015 Community.
Thanks

**Comment by mlorbetske** [comment]
Visual Studio 2017 forward should be supported by the extension

**Comment by mophdog** [comment]
@mlorbetske I've just been looking for this exact functionality in VS2022 and alas, this VS2019 extension is the closest I've found.

Appreciate this project is unlikely to be updated, but might you be able to recommend an alternative approach to getting a breakpoint / stack trace when an assembly is loaded?

**Comment by mlorbetske** [comment]
Funny enough, I was just thinking of this project the other day. Let me see if I can make it work on 2022. I unfortunately don't know of any other extensions that do the same thing, but I haven't looked in quite some time, since I don't often work on extensions these days.

**Comment by mophdog** [comment]
I have zero experience in VS extensions, but I'll pull the code and see if I can make a meaningful contribution.
